#!/bin/bash
set -e
source /usr/lib/frr/frrcommon.sh

echo "[INFO] Iniciando SNMP, Telegraf y FRR"

if [ -f /mnt/influx-creds/creds.env ]; then
  export $(cat /mnt/influx-creds/creds.env | xargs)
else
  echo "[WARN] No se encontró /mnt/influx-creds/creds.env"
fi

envsubst < /etc/telegraf/telegraf.conf.template > /etc/telegraf/telegraf.conf

#/usr/sbin/snmpd -f -Lo &
/usr/bin/telegraf --config /etc/telegraf/telegraf.conf &
/usr/lib/frr/frrinit.sh start

wait -n
